services:
  app:
    image: mosaicrag:latest
    container_name: mosaic-app
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - OLLAMA_HOST=172.17.0.1:11434
      - COLOR_THEME=blue-light
      - APP_TITLE=
      - APP_SUBTITLE=
      - APP_DEFAULT_PIPELINE={"1":{"id":"mosaic_datasource","parameters":{"output_column":"full-text","url":"https://mosaic.ows.eu/service/api","limit":"20","search_index":"simplewiki"}}}
      - LITELLM_URL=
      - LITELLM_APIKEY=
      - LITELLM_MODELS=

    depends_on:
      - redis
    networks:
      - mosaic-net

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - mosaic-net
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  mosaic-net: